---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../collections/requirements.yml
driver:
  name: docker
platforms:
  - name: nginx-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: nginx-centos
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    host_vars:
      nginx-ubuntu:
        ansible_python_interpreter: /usr/bin/python3
      nginx-centos:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
