# Production Web Server 2 Variables
ansible_host: 172.16.1.11
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/prod_key

# Application configuration
webapp_app_name: webapp-prod
app_port: 8080
app_environment: production

# Non-sensitive variables
nginx_worker_processes: 3
nginx_worker_connections: 2048

# Encrypted sensitive variables (shared prod environment secrets)
vault_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          326236643436303732383038313138303732316265653536333064303532633323531623366666433
          3534663634653131373064616231323530316261306639340a3330666530623353364356531653235
          653336323238623361623465313236656336336131326261356363393132633353761653639393562
          6334623866356331610a3861373464323161633366646463386232623333313336666386166303432
          353038353663353037636338363664313837326635613635383230666263613343064

vault_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          646137623934396266643531373235626638666238383563393231363530636653336626332336465
          3665633839363535366265646466393332633030356531340a3330646661643336539636435386262
          343533646134663834303865326635656135353139306532386637366230343373161613833653262
          3132383832393937360a6539643934333338373730373938336636303763653313333356632653465
          346637383736613061383433336632323465623030383362326466396139643353666613061336632
          3333633765653765663163393634393561633536383830326139

vault_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          303263353563343830313132636134633066663665313666313638646662373386230386366633536
          3964336134623737346262643064663265326438656463650a3064353738633323739653739373135
          653832636437363835656239393365663936323334396236373064666266346646234353062363266
          3066303739363534300a3131376139383334623665313132373338393464313303665326164313935
          306466353639336233613439656466373433353636353236316234306166626623437
